version: "3.8"

services:
  # Nacos Server
  Nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    restart: always
    ports:
      - "8848:8848"  # web 界面访问端口
      - "9848:9848"  # 程序使用 grpc 连接的端口
      - "9849:9849"  # 程序使用 grpc 连接的端口
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_IDENTITY_KEY=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      - NACOS_AUTH_IDENTITY_VALUE=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
    volumes:
      - ./nacos_data/logs:/home/nacos/logs

  # PostgresSQL Server
  PostgresSQL:
    image: postgres:16.10
    container_name: postgres-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_PASSWORD=SmarkWork@2025
    volumes:
      - ./db_data/data:/var/lib/postgresql/data
      - ./db_data/log:/var/log/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 5

  # TDengine Server
  TDengine:
    image: tdengine/tdengine:3.3.0.0
    container_name: tdengine-server
    privileged: true
    restart: always
    ports:
      - "6030:6030"
      - "6041:6041"
      - "6060:6060"
      - "6043-6049:6043-6049/tcp"
      - "6043-6049:6043-6049/udp"
    volumes:
      - './taos_data/data:/var/lib/taos'
      - './taos_data/log:/var/log/taos'

  # Redis Server
  Redis:
    image: redis:7.2.9
    container_name: redis-server
    restart: always
    privileged: true
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Shanghai
    command: redis-server --save 60 1000 --loglevel warning --appendonly yes --requirepass SmarkWork@2025
    volumes:
      - './redis_data/data:/data'
      - './redis_data/logs:/logs'
    logging:
      driver: "json-file"
      options:
        max-size: "20M"
        max-file: "10"

  # kafka
  Kafka:
    image: apache/kafka:3.8.0
    container_name: kafka-server
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://localhost:9092'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SHARE_COORDINATOR_STATE_TOPIC_MIN_ISR: 1
      CLUSTER_ID: '4L6g3nShT-eMCtK--X86sw'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - ./mq_data/data:/var/lib/kafka/data
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "Local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"


# 磁盘挂载
volumes:
  nacos_data:
    driver: local
  db_data:
    driver: local
  taos_data:
    driver: local
  redis_data:
    driver: local
  mq_data:
    driver: local