services:
  # Harbor Log
  log:
    image: goharbor/harbor-log:v2.10.0
    container_name: harbor-log
    restart: always
    volumes:
      - ./harbor_data/log:/var/log/docker/:z
    networks:
      - harbor-network

  # Harbor Registry
  registry:
    image: goharbor/registry-photon:v2.10.0
    container_name: registry
    restart: always
    volumes:
      - ./harbor_data/registry:/storage:z
      - ./harbor_data/registryctl:/etc/registryctl:z
      - type: bind
        source: ./common/config/registry/registryctl.yml
        target: /etc/registryctl/config.yml
    networks:
      - harbor-network
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registry"

  # Harbor Registry Controller
  registryctl:
    image: goharbor/harbor-registryctl:v2.10.0
    container_name: registryctl
    env_file:
      - ./common/config/registryctl/env
    restart: always
    volumes:
      - ./harbor_data/registry:/storage:z
      - ./harbor_data/registryctl:/etc/registryctl:z
      - type: bind
        source: ./common/config/registry/registryctl.yml
        target: /etc/registryctl/config.yml
    networks:
      - harbor-network
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "registryctl"

  # Harbor PostgreSQL Database
  postgresql:
    image: goharbor/harbor-db:v2.10.0
    container_name: harbor-db
    restart: always
    volumes:
      - ./harbor_data/database:/var/lib/postgresql/data:z
    networks:
      - harbor-network
    env_file:
      - ./common/config/db/env
    depends_on:
      - log
    shm_size: '1gb'
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "postgresql"

  # Harbor Core
  core:
    image: goharbor/harbor-core:v2.10.0
    container_name: harbor-core
    env_file:
      - ./common/config/core/env
    restart: always
    volumes:
      - ./harbor_data/ca_download/:/etc/core/ca/:z
      - ./harbor_data/:/data/:z
      - type: bind
        source: ./common/config/core/app.conf
        target: /etc/core/app.conf
      - type: bind
        source: ./common/config/core/private_key.pem
        target: /etc/core/private_key.pem
      - type: bind
        source: ./common/config/core/root.crt
        target: /etc/core/root.crt
    networks:
      - harbor-network
      - easyaiot-network
    depends_on:
      - log
      - registry
      - redis
      - postgresql
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "core"

  # Harbor Job Service
  jobservice:
    image: goharbor/harbor-jobservice:v2.10.0
    container_name: harbor-jobservice
    env_file:
      - ./common/config/jobservice/env
    restart: always
    volumes:
      - ./harbor_data/job_logs:/var/log/jobs:z
      - type: bind
        source: ./common/config/jobservice/config.yml
        target: /etc/jobservice/config.yml
    networks:
      - harbor-network
    depends_on:
      - log
      - redis
      - core
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "jobservice"

  # Harbor Redis
  redis:
    image: goharbor/redis-photon:v2.10.0
    container_name: redis
    restart: always
    volumes:
      - ./harbor_data/redis:/var/lib/redis
    networks:
      - harbor-network
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "redis"

  # Harbor Proxy (Nginx)
  proxy:
    image: goharbor/nginx-photon:v2.10.0
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx:/etc/nginx:z
    networks:
      - harbor-network
      - easyaiot-network
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - log
      - registry
      - core
      - jobservice
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://localhost:1514"
        tag: "proxy"

# 磁盘挂载
volumes:
  harbor_data:
    driver: local

# 网络配置
networks:
  harbor-network:
    name: harbor-network
    driver: bridge
  easyaiot-network:
    name: easyaiot-network
    external: true

